### ISSUE TITLE
Size/speed improvements

### ISSUE THREAD

**Issue by fadden** [fadden/fhpack#1]
From qkumba on comp.sys.apple2 (https://groups.google.com/forum/#!topic/comp.sys.apple2/SDgtVW3h4is) ...

 ===
Thinking about the performance of this (because my original LZ4 code was optimised for size, not speed) - sequences like this one: 

 bcc :nohi 
 inc srcptr+1 
:nohi 

and this one in particular: 

 inc srcptr 
 bne :nohi 
 inc srcptr+1 
:nohi 

would probably benefit from this instead: 

 inc srcptr 
 beq :incsp1 
:nohi 

... 

:incsp1 
inc srcptr+1 
bne :nohi ;assuming that your source won't be in the $ff00 range. 

to save 1 cycle per low increment, so there's a 4 cycle hit only once per high increment. 
 ===

 ===
One byte saving: 

:nohi1 
 ldy #$ff ;next INY rolls back to zero 

can be DEY because Y is always 00 already at that point. 
## 

Two bytes and two cycles saving: 

 sta savmix 
and 
 lda savmix 

can be TAX and TXA. 
## 

One byte and two cycles saving: 

 clc 
 adc #15 ;add 15 - will not exceed 255 
- At this point, srcptr holds the address of the "mix" 

carry is always set at that point, you can adc #14 and discard the clc. 
 ===

**Comment by peterferrie** [comment]
bcc :nohi
 inc srcptr+1
:nohi
...
- advance dstptr past copied data
  lda dstptr
  clc

That clc should move to before the :nohi to save 2 cycles per match in most cases (carry is already clear if only low part was incremented).

## 

also replacing this:

 bcc :nohi1
 inc dstptr+1
:nohi1

 DO overrun_check
 LDA dstptr+1
 CMP #$60
 BLT :OKAY
 BRK
 BRK
:OKAY
 jmp mainloop
 ELSE
 bne mainloop ;branch always
 FIN

with this

 bcc mainloop
 inc dstptr+1
 DO overrun_check
 LDA dstptr+1
 CMP #$60
 BLT mainloop
 BRK
 BRK
 ELSE
 bne mainloop ;branch always
 FIN

will save 3 cycles per low increment, and 3 cycles per overrun check.
no need to perform the overrun check on every low increment.

**Comment by peterferrie** [comment]
if you're short on space, and can accept a 5 cycle hit, you can defer this:
- Advance srcptr past the encoded match while we still
  by a pha or a sta
  and then branch a couple of instructions past the specialmatch code to update srcptr.

speaking of which, in specialmatch,  "bcc :nohi" should be "bcc mainloop" to save 3 cycles per low increment, and the clc can be discarded because the value is destroyed anyway by mainloop.

**Comment by fadden** [comment]
"bcc mainloop" will only work if you've managed to cut about 9 bytes out of the middle... it's just out of range.

03B1-   90 03       BCC   $03B6
03B3-   E6 3D       INC   $3D
03B5-   18          CLC
03B6-   4C 28 03    JMP   $0328

I think the CLC is vestigial, from an earlier iteration that wanted a clear carry at the start of mainloop.

The overrun check is disabled by default -- I added it when I had a bug.  It uses JMP rather than BNE because, at the time I wrote it, it made the code a couple bytes longer than relative-branch range.

**Comment by peterferrie** [comment]
major pull request coming soon.  I've reordered some things - no jmp anywhere.

**Comment by peterferrie** [comment]
down to 194 bytes

**Comment by fadden** [comment]
Merged in at https://github.com/fadden/fhpack/commit/9221ef09d11a0f5f4cbbfea5f9a2a1340e934b17 .
